baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Somos Bridges'
theme = 'marketing-site'
relativeURLS = true

[module]
  [[module.mounts]]  
    source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
    target = "assets/js/bootstrap.bundle.min.js"